language: objective-c
osx_image: xcode8.3

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - cd example && yarn && cd ..
  - cd example/ios && pod install && cd ../..
  - cd example && ./node_modules/.bin/react-native link react-native-analytics-segment-io && cd ..

script:
  - xcodebuild clean build -sdk iphonesimulator -workspace example/ios/example.xcworkspace -scheme example CODE_SIGNING_REQUIRED=NO
